services:
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ".db:/data/db"
    scrapper:
        build: "."
        links:
            - db
        environment:
            TELEGRAM_API_ID: ${TELEGRAM_API_ID}
            TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
            SIMPLE_SETTINGS: settings.base
        volumes:
            - "./telegram.session:/app/telegram.session"
        command: ["python", "/app/scrapper.py"]
    api:
        build: "."
        links:
            - db
        environment:
            API_LISTEN: "127.0.0.1:8000"
            SIMPLE_SETTINGS: settings.base
        ports:
            - "8000:8000"
        command: ["python", "/app/api.py"]